name: Update MongoDB

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  update-mongodb:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Update package lists
        run: |
          echo "Updating package lists..."
          sudo apt-get update

      - name: Install wget and gdebi
        run: |
          echo "Installing wget and gdebi..."
          sudo apt install -y wget gdebi

      - name: Download MongoDB Tools
        run: |
          echo "Downloading MongoDB Tools..."
          wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2404-x86_64-100.10.0.deb -O mongodb-tools.deb

      - name: Install MongoDB Tools
        run: |
          echo "Installing MongoDB Tools..."
          sudo gdebi -n mongodb-tools.deb

      - name: Import Data
        run: |
          echo "Importing data into MongoDB..."
          for file in src/*.json; do
            collection=$(basename "$file" .json | tr '[:upper:]' '[:lower:]')
            echo "Importing $file into collection $collection..."
            mongoimport --uri mongodb+srv://${{ secrets.MONGO_USER }}:${{ secrets.MONGO_PASSWORD }}@${{ vars.MONGO_HOST }}/${{ vars.MONGO_DATABASE }} --collection "$collection" --type json --file "$file" --jsonArray --drop
          done